name: Nightly ss58-registry check
on:
  schedule:
    - cron:  '1 * * * *'

jobs:
  ss58:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: test
      run: |
        echo 'auto-created from CI' > ./issue_template
        echo >> ./issue_template
        yarn install --immutable | grep -v 'YN0013'
        yarn test:networks

    - name: Create issue for failure
      if: ${{ failure() }}
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: SS58 registry is outdated compared to Substrate master
        labels: ci
        content-filepath: ./issue_template
        token: ${{ secrets.GH_PAT }}
